package com.oracle.springboot.pojo;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.type
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parentId
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.createdate
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.modifydate
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.dianzan
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    private Integer dianzan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.createUser
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    private Long createuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.type
     *
     * @return the value of comment.type
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.type
     *
     * @param type the value for comment.type
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parentId
     *
     * @return the value of comment.parentId
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parentId
     *
     * @param parentid the value for comment.parentId
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.createdate
     *
     * @return the value of comment.createdate
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.createdate
     *
     * @param createdate the value for comment.createdate
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.modifydate
     *
     * @return the value of comment.modifydate
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.modifydate
     *
     * @param modifydate the value for comment.modifydate
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.dianzan
     *
     * @return the value of comment.dianzan
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public Integer getDianzan() {
        return dianzan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.dianzan
     *
     * @param dianzan the value for comment.dianzan
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public void setDianzan(Integer dianzan) {
        this.dianzan = dianzan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.createUser
     *
     * @return the value of comment.createUser
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public Long getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.createUser
     *
     * @param createuser the value for comment.createUser
     *
     * @mbggenerated Mon Sep 16 17:01:12 CST 2019
     */
    public void setCreateuser(Long createuser) {
        this.createuser = createuser;
    }
}