package com.oracle.springboot.pojo;

import java.util.Date;

public class Likes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.id
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.parentId
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.user
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    private Long user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.type
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.createdate
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column likes.status
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.id
     *
     * @return the value of likes.id
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.id
     *
     * @param id the value for likes.id
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.parentId
     *
     * @return the value of likes.parentId
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.parentId
     *
     * @param parentid the value for likes.parentId
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.user
     *
     * @return the value of likes.user
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    public Long getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.user
     *
     * @param user the value for likes.user
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    public void setUser(Long user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.type
     *
     * @return the value of likes.type
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.type
     *
     * @param type the value for likes.type
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.createdate
     *
     * @return the value of likes.createdate
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.createdate
     *
     * @param createdate the value for likes.createdate
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column likes.status
     *
     * @return the value of likes.status
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column likes.status
     *
     * @param status the value for likes.status
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}