package com.oracle.springboot.pojo;

import java.util.Date;

public class Notification {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.fabu
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    private Long fabu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.jieshou
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    private Long jieshou;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.outerId
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    private Long outerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.type
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.createdate
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.status
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notifierName
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    private String notifiername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.questionTitle
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    private String questiontitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.fabu
     *
     * @return the value of notification.fabu
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public Long getFabu() {
        return fabu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.fabu
     *
     * @param fabu the value for notification.fabu
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public void setFabu(Long fabu) {
        this.fabu = fabu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.jieshou
     *
     * @return the value of notification.jieshou
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public Long getJieshou() {
        return jieshou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.jieshou
     *
     * @param jieshou the value for notification.jieshou
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public void setJieshou(Long jieshou) {
        this.jieshou = jieshou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.outerId
     *
     * @return the value of notification.outerId
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.outerId
     *
     * @param outerid the value for notification.outerId
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.type
     *
     * @return the value of notification.type
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.type
     *
     * @param type the value for notification.type
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.createdate
     *
     * @return the value of notification.createdate
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.createdate
     *
     * @param createdate the value for notification.createdate
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.status
     *
     * @return the value of notification.status
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.status
     *
     * @param status the value for notification.status
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notifierName
     *
     * @return the value of notification.notifierName
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public String getNotifiername() {
        return notifiername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notifierName
     *
     * @param notifiername the value for notification.notifierName
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public void setNotifiername(String notifiername) {
        this.notifiername = notifiername == null ? null : notifiername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.questionTitle
     *
     * @return the value of notification.questionTitle
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public String getQuestiontitle() {
        return questiontitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.questionTitle
     *
     * @param questiontitle the value for notification.questionTitle
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    public void setQuestiontitle(String questiontitle) {
        this.questiontitle = questiontitle == null ? null : questiontitle.trim();
    }
}