package com.oracle.springboot.pojo;

import java.util.Date;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.createdate
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.modifydate
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.createUser
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    private Long createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.yuedu
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    private Integer yuedu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.dianzan
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    private Integer dianzan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.pinglun
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    private Integer pinglun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.tag
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.description
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.createdate
     *
     * @return the value of question.createdate
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.createdate
     *
     * @param createdate the value for question.createdate
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.modifydate
     *
     * @return the value of question.modifydate
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.modifydate
     *
     * @param modifydate the value for question.modifydate
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.createUser
     *
     * @return the value of question.createUser
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public Long getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.createUser
     *
     * @param createuser the value for question.createUser
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public void setCreateuser(Long createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.yuedu
     *
     * @return the value of question.yuedu
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public Integer getYuedu() {
        return yuedu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.yuedu
     *
     * @param yuedu the value for question.yuedu
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public void setYuedu(Integer yuedu) {
        this.yuedu = yuedu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.dianzan
     *
     * @return the value of question.dianzan
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public Integer getDianzan() {
        return dianzan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.dianzan
     *
     * @param dianzan the value for question.dianzan
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public void setDianzan(Integer dianzan) {
        this.dianzan = dianzan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.pinglun
     *
     * @return the value of question.pinglun
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public Integer getPinglun() {
        return pinglun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.pinglun
     *
     * @param pinglun the value for question.pinglun
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public void setPinglun(Integer pinglun) {
        this.pinglun = pinglun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.tag
     *
     * @return the value of question.tag
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.tag
     *
     * @param tag the value for question.tag
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.description
     *
     * @return the value of question.description
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.description
     *
     * @param description the value for question.description
     *
     * @mbggenerated Fri Sep 27 10:05:44 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}