package com.oracle.springboot.dao;

import com.oracle.springboot.pojo.Likes;
import com.oracle.springboot.pojo.LikesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.PathVariable;

@Repository
public interface LikesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    int countByExample(LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    int deleteByExample(LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    int insert(Likes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    int insertSelective(Likes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    List<Likes> selectByExample(LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    Likes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") Likes record, @Param("example") LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    int updateByExample(@Param("record") Likes record, @Param("example") LikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    int updateByPrimaryKeySelective(Likes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table likes
     *
     * @mbggenerated Sat Oct 12 10:12:45 CST 2019
     */
    int updateByPrimaryKey(Likes record);


    @Select("select * from `likes` where user=#{userId} order by createdate  desc limit #{offset},#{size}")
    List<Likes> getLikesPageByUser(@PathVariable(value = "userId")Long userId, @Param(value = "offset") Integer offset, @Param(value = "size")  Integer size);
}