package com.oracle.springboot.dao;

import com.oracle.springboot.bean.QuestionQueryDto;
import com.oracle.springboot.pojo.Notification;
import com.oracle.springboot.pojo.NotificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.PathVariable;

@Repository
public interface NotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    //9.25改
    int countByExample(NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    int deleteByExample(NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    int insert(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    int insertSelective(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    List<Notification> selectByExample(NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    Notification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") Notification record, @Param("example") NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    int updateByExample(@Param("record") Notification record, @Param("example") NotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    int updateByPrimaryKeySelective(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Sep 25 09:56:03 CST 2019
     */
    int updateByPrimaryKey(Notification record);

    @Select("select * from `notification` where jieshou=#{userId} order by createdate  desc limit #{offset},#{size}")
    List<Notification> PageListByUser(@PathVariable(value = "userId")Long userId, @Param(value = "offset") Integer offset, @Param(value = "size")  Integer size);

    @Select({"<script>","select * from `notification` where ORDER BY createdate Desc limit ","<when test='search!=null'>","#{page},#{size}","</when>","</script>"})
    List<Notification> selectDoomsd(QuestionQueryDto questionQueryDto);
}