package com.oracle.springboot.dao;

import com.oracle.springboot.bean.QuestionQueryDto;
import com.oracle.springboot.pojo.Comment;
import com.oracle.springboot.pojo.Question;
import com.oracle.springboot.pojo.QuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.PathVariable;
@Repository
public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    int countByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    int deleteByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    List<Question> selectByExampleWithBLOBs(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    List<Question> selectByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    Question selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    int updateByExample(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Oct 14 16:55:21 CST 2019
     */
    int updateByPrimaryKey(Question record);


    Integer countBySearch(QuestionQueryDto questionQueryDto);

    List<Question> selectBySearch(QuestionQueryDto questionQueryDto);

    @Select("select * from `question` ORDER BY createdate Desc limit #{offset},#{size}")
    List<Question> PageList(Integer offset, Integer size);

    @Select("select count(1) from `question` where status=#{status} and createUser=#{userId}")
    Integer countByUser(@Param(value = "userId")Long userId,@Param(value = "status") Integer status);

    @Select("select * from `question` where status=#{status} and createUser=#{userId} ORDER BY createdate Desc limit #{offset},#{size}")
    List<Question> PageListByUser(@Param(value = "userId")Long userId, @Param(value = "offset") Integer offset, @Param(value = "size")  Integer size,@Param(value = "status")Integer status);

    @Update("update `question`  SET YUEDU=YUEDU+1 where id=#{id}")
    void updateYueDu(Long id);

    @Update("update `question`  SET PINGLUN=PINGLUN+1 where id=#{parentid}")
    void updatePingLun(Comment comment);

    @Select("SELECT * FROM `question` WHERE ID=#{questionId}")
    Question getQuestionById(Long parentid);

    @Select("SELECT * FROM `question` where id!=#{id} and tag regexp #{tag}")
    List<Question> selectTag(Question question);

    @Update("update `question` SET DIANZAN=DIANZAN+1 where id=#{id}")
    void dianzan(Long id);

    @Update("update `question` SET status=#{status} where id=#{id}")
    void update(Long id, Integer status);


}